name: Build (macOS M1)

on: [workflow_dispatch]

jobs:

  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-14
            target: ARM64
            cmd-install: |
              python -m venv env
              source env/bin/activate
              python -m pip install --upgrade pip
              python -m pip install -r requirements.txt
            cmd-build: |
              cd standalone
              ../env/bin/pyinstaller console_arm64.spec
              cd dist
              mv mltd-relive-standalone mltd-relive-standalone-arm64
            out-name: mltd-relive-standalone-arm64
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies for ${{ matrix.target }}
      run: ${{ matrix.cmd-install }}    
    - name: Build with PyInstaller for ${{ matrix.target }}
      run: ${{ matrix.cmd-build }}
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.out-name }}
        path: standalone/dist
